# Generated by Django 2.0.3 on 2018-05-15 22:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_sessao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f7e06419-f760-4e67-97ad-1a37124aff30'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
