# Generated by Django 2.0.3 on 2018-05-16 00:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20180515_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2e5271a1-a29b-40ce-af83-c0208d5a37cd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
