# Generated by Django 2.0.3 on 2018-05-16 01:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20180515_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fbe385a6-d380-4ed5-95e1-bda71769f19d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
