# Generated by Django 2.0.3 on 2018-05-16 01:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20180515_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='id',
            field=models.UUIDField(default=uuid.UUID('17aae4e8-6445-4b71-b1e2-7285820ab24d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
