# Generated by Django 2.0.3 on 2018-05-16 01:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20180515_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='id',
            field=models.UUIDField(default=uuid.UUID('15586339-0643-4959-ba44-95a09fe29f78'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
