# Generated by Django 2.0.3 on 2018-05-16 01:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20180515_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b5bc6ede-b2de-4694-8dd2-ddd40f748f7b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
