# Generated by Django 2.0.3 on 2018-05-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculo',
            name='qtdHora',
            field=models.IntegerField(verbose_name='QTD Hora'),
        ),
    ]
